### PR TITLE
Trivial typo fix

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
Oh.  Just noticed this wasn't merged.  Was it wrong?

**Comment by noartem** [comment]
Sorry, I did not see the change in the pull request, because I thought that this refers to issue

**Comment by noartem** [comment]
Sorry, I did not see the change in the pull request, because I thought that this refers to issue

**Comment by justinclift** [comment]
No worries.  I was just thinking "childes" was meant to be "children": :smile:

https://github.com/gascore/gas/blob/master/web/element.go#L77

**Pull request closed without merging**
